import { siteConfig } from "@/lib/site-config";

export interface ChannelUpload {
  youtubeId: string;
  title: string;
  publishedAt: string;
}

/**
 * Latest uploads from the Swarangan YouTube channel.
 *
 * Uses the channel's public RSS feed, which needs no API key, no OAuth and has
 * no quota — so the "latest videos" section stays inside the free tier
 * permanently. The YouTube Data API would need a key and a billing-linked
 * project for the same information.
 *
 * Deliberately forgiving: any failure returns an empty list so the page still
 * renders its curated content. A broken third-party feed must never take the
 * site down.
 *
 * STATUS (verified against the live Swarangan channel): YouTube currently
 * answers this endpoint with 404/500 for this channel, even though the channel
 * id is correct and the channel itself resolves. Google has been restricting
 * these feeds. The consequence is simply that the "Latest uploads" section does
 * not render — the curated list in src/content/social.ts is the primary
 * mechanism and is unaffected. Kept because it costs nothing, needs no key, and
 * starts working again by itself if the endpoint is restored.
 */
const FEED_URL = `https://www.youtube.com/feeds/videos.xml?channel_id=${siteConfig.social.youtubeChannelId}`;

/** Entries are small; this guards against a hung request blocking the render. */
const TIMEOUT_MS = 4000;

export async function latestChannelUploads(): Promise<ChannelUpload[]> {
  try {
    const response = await fetch(FEED_URL, {
      // Cached by Next for an hour; matches the page's revalidate.
      next: { revalidate: 3600 },
      signal: AbortSignal.timeout(TIMEOUT_MS),
    });
    if (!response.ok) return [];

    return parseFeed(await response.text());
  } catch {
    // Network error, timeout, or malformed feed — fall back to curated content.
    return [];
  }
}

/**
 * Minimal Atom parsing.
 *
 * A full XML parser would be a dependency for one well-known, stable feed shape.
 * The feed is machine-generated by YouTube, so the fields are always present in
 * the same form; anything unexpected is skipped rather than guessed at.
 */
export function parseFeed(xml: string): ChannelUpload[] {
  const uploads: ChannelUpload[] = [];

  for (const entry of xml.split("<entry>").slice(1)) {
    const youtubeId = between(entry, "<yt:videoId>", "</yt:videoId>");
    const title = between(entry, "<title>", "</title>");
    const publishedAt = between(entry, "<published>", "</published>");
    if (!youtubeId || !title) continue;

    uploads.push({
      youtubeId,
      title: decodeEntities(title),
      publishedAt: publishedAt ?? "",
    });
  }

  return uploads;
}

function between(source: string, open: string, close: string): string | null {
  const start = source.indexOf(open);
  if (start === -1) return null;
  const end = source.indexOf(close, start + open.length);
  if (end === -1) return null;
  return source.slice(start + open.length, end).trim();
}

/** The five XML predefined entities, plus numeric escapes YouTube emits. */
function decodeEntities(value: string): string {
  return (
    value
      .replace(/&lt;/g, "<")
      .replace(/&gt;/g, ">")
      .replace(/&quot;/g, '"')
      .replace(/&apos;/g, "'")
      .replace(/&#(\d+);/g, (_, code: string) =>
        String.fromCodePoint(Number(code)),
      )
      .replace(/&#x([0-9a-f]+);/gi, (_, code: string) =>
        String.fromCodePoint(Number.parseInt(code, 16)),
      )
      // Ampersand last, so a decoded "&amp;lt;" cannot become a tag.
      .replace(/&amp;/g, "&")
  );
}
