/**
 * Restore a Swarangan backup ZIP into a Supabase project.
 *
 *   npm run restore -- path/to/swarangan-backup-….zip            (dry run)
 *   npm run restore -- path/to/swarangan-backup-….zip --confirm  (writes)
 *
 * Reads NEXT_PUBLIC_SUPABASE_URL and SUPABASE_SECRET_KEY from .env.local (or
 * the environment). Run the migration in supabase/migrations first on a fresh
 * project.
 *
 * WHAT IT DOES
 *   - Checks the file is a Swarangan backup of a version this script knows.
 *   - Upserts every table in the order the backup lists them (parents before
 *     children), keyed on each row's id or key: existing rows are overwritten
 *     with the backup's values, rows not in the backup are left alone.
 *   - Without --confirm it only reports what it would do.
 *
 * WHAT IT DOES NOT
 *   - admin_audit_log is skipped: its ids are generated by the database and
 *     cannot be written back. The history stays readable in the backup's CSV.
 *   - Photos are not in the backup; they live in Supabase Storage.
 *   - Admins are re-added by hand, per SETUP.md.
 */
import { createClient } from "@supabase/supabase-js";
import { strFromU8, unzipSync } from "fflate";
import { existsSync, readFileSync } from "node:fs";

// ---- Environment (same loader as verify-rls) -----------------------------
if (existsSync(".env.local")) {
  for (const line of readFileSync(".env.local", "utf8").split(/\r?\n/)) {
    const match = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*)\s*$/);
    if (match && !process.env[match[1]]) {
      process.env[match[1]] = match[2].replace(/^["']|["']$/g, "");
    }
  }
}

const args = process.argv.slice(2);
const file = args.find((arg) => !arg.startsWith("--"));
const confirm = args.includes("--confirm");
const SKIPPED = new Set(["admin_audit_log"]);
const BATCH = 500;

if (!file || !existsSync(file)) {
  console.error("Usage: npm run restore -- <backup.zip> [--confirm]");
  process.exit(1);
}

const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
const secretKey = process.env.SUPABASE_SECRET_KEY;
if (!url || !secretKey) {
  console.error("Set NEXT_PUBLIC_SUPABASE_URL and SUPABASE_SECRET_KEY first.");
  process.exit(1);
}

// ---- Read and check the backup -------------------------------------------
const files = unzipSync(readFileSync(file));
const read = (name) => {
  if (!files[name]) throw new Error(`The backup is missing ${name}.`);
  return JSON.parse(strFromU8(files[name]));
};

const manifest = read("manifest.json");
if (manifest.format !== "swarangan-backup" || manifest.version !== 1) {
  console.error("This is not a Swarangan backup this script can restore.");
  process.exit(1);
}

console.log(
  `Backup made ${manifest.createdAt} by ${manifest.createdBy ?? "unknown"}`,
);
console.log(`Target: ${url}`);
console.log(
  confirm ? "Mode: RESTORING\n" : "Mode: dry run (add --confirm to write)\n",
);

// A row identifies itself by id, or by key for the tables keyed by name.
const conflictColumn = (rows) =>
  rows.length > 0 && "key" in rows[0] && !("id" in rows[0]) ? "key" : "id";

const db = createClient(url, secretKey, {
  auth: { persistSession: false, autoRefreshToken: false },
});

let failed = false;
for (const { name, rows: expected } of manifest.tables) {
  if (SKIPPED.has(name)) {
    console.log(`  skip     ${name} (kept in the backup's CSV only)`);
    continue;
  }
  const rows = read(`json/${name}.json`);
  if (rows.length !== expected) {
    console.error(
      `  MISMATCH ${name}: manifest says ${expected}, file has ${rows.length}`,
    );
    failed = true;
    continue;
  }
  if (!confirm || rows.length === 0) {
    console.log(
      `  ${confirm ? "empty   " : "would   "} ${name}: ${rows.length} rows`,
    );
    continue;
  }

  const onConflict = conflictColumn(rows);
  for (let i = 0; i < rows.length; i += BATCH) {
    const { error } = await db
      .from(name)
      .upsert(rows.slice(i, i + BATCH), { onConflict });
    if (error) {
      console.error(`  FAILED   ${name}: ${error.message}`);
      failed = true;
      break;
    }
  }
  if (!failed) console.log(`  restored ${name}: ${rows.length} rows`);
}

if (failed) {
  console.error(
    "\nFinished with errors. Fix the cause and run again; it is safe to repeat.",
  );
  process.exit(1);
}
console.log(
  confirm ? "\nRestore complete." : "\nDry run complete. Nothing was written.",
);
