import Image, { type ImageProps } from "next/image";

import {
  imageManifest,
  type ImageKey,
} from "@/content/generated/image-manifest";
import { cn } from "@/lib/utils";

type SwarImageProps = Omit<
  ImageProps,
  "src" | "width" | "height" | "alt" | "blurDataURL" | "placeholder"
> & {
  /** Key into the generated manifest, e.g. "events/af2024-ensemble.jpg". */
  image: ImageKey;
  /**
   * Override the manifest's alt text. Pass "" only for an image that is purely
   * decorative and already described by adjacent copy.
   */
  alt?: string;
};

/**
 * The one image component.
 *
 * Pulls intrinsic dimensions, alt text and a blur placeholder from the manifest
 * generated by scripts/build-assets.mjs, so no call site can omit a dimension
 * (layout shift) or forget alt text (accessibility). Replacing a photo is a
 * re-run of the asset script, not an edit here.
 */
export function SwarImage({ image, alt, className, ...rest }: SwarImageProps) {
  const entry = imageManifest[image];

  return (
    <Image
      src={entry.src}
      width={entry.width}
      height={entry.height}
      alt={alt ?? entry.alt}
      placeholder="blur"
      blurDataURL={entry.blurDataURL}
      className={cn("h-auto w-full", className)}
      {...rest}
    />
  );
}

/** Dimensions and alt text for an image, for callers that need the raw values. */
export function getImage(image: ImageKey) {
  return imageManifest[image];
}

const BLUR_BY_SRC = new Map<string, string>(
  Object.values(imageManifest).map((entry) => [entry.src, entry.blurDataURL]),
);

/**
 * The build-time blur placeholder for an image that ships with the site, looked
 * up by its path. Photos uploaded through the admin have none, and get undefined
 * rather than a crash.
 */
export function blurFor(src: string): string | undefined {
  return BLUR_BY_SRC.get(src);
}
